ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - name: Rails Server
    init: bundle install && yarn install --check-files && bundle exec rails db:migrate db:seed
    command: bundle exec rails server
  - name: Test
    init: bundle install && yarn install --check-files && RAILS_ENV=test bundle exec rails db:migrate
    command: bundle exec rspec